name: Build SecureVault Browser - macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download Chromium
      run: |
        # Download latest Chromium for macOS
        curl -L -o chromium.zip https://download-chromium.appspot.com/dl/Mac?type=snapshots
        
    - name: Extract and Rebrand
      run: |
        mkdir -p build/macos
        # TODO: Extract, apply branding
        echo "Chromium extracted - rebranding step would go here"
        
    - name: Package
      run: |
        mkdir -p dist
        # Create DMG
        echo "Creating macOS DMG"
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: securevault-browser-macos
        path: dist/*
        retention-days: 90
